---
# ansible_become_pass: "{{ ubuntu_become_pass }}"
pic_dir: "{{ ansible_user_dir }}/Pictures/"
bg_img_url: https://cdn.wallpapersafari.com/55/73/ghY4rc.jpg
dest_pic_filename: bg.jpg

servers:
  - galaxy
  - vulcan
  - ameros

php_version: 8.3

base_packages:
  - htop
  - vim
  - kazam
  - filezilla
  - bluefish
  - "php{{ php_version }}"
